services:
  mysql:
    image: mysql:8.4
    container_name: examhub-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: examhub
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - examhub-mysql:/var/lib/mysql

volumes:
  examhub-mysql:
